language: swift

osx_image: xcode10.1

branches:
  only:
    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8

podfile: Podfile

xcode_workspace: Groshy.xcworkspace
xcode_scheme: Groshy
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone XS

before_install:
    - pod repo update