language: swift

osx_image: xcode10.1

podfile: Podfile

xcode_workspace: Groshy.xcworkspace
xcode_scheme: Groshy
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone XS

before_install:
    - pod repo update